### ISSUE TITLE
Password reset doesn't work, but unknown why

### ISSUE THREAD

**Issue by Tuxified** [kabisa/kudo-o-matic#356]
I tried resetting my password (as I was using Google login, not personal). After I entered my email, the form tells me I did something wrong, but won't tell me what?

![image](https://user-images.githubusercontent.com/51889/42685191-9e5bf76a-8692-11e8-8837-51dbf50c30a3.png)

**Comment by ariejan** [comment]
The problem is you have not account with `tonci.galic`, just `tonci`.

This may have happened because Google, a while back, changed sign in a bit. You're no longer allowed to sign in with an alias (`tonci`) but need to use your full account email: `tonci.galic`. 

The form is not the most pretty in existence, but we'll address that separately.

**Comment by Tuxified** [comment]
My point wasn't about me not being unable to login, but about the unclear message the form shows. It tells me to 'review the problems below' but no clue what those problems are. I figured out the correct username by trial-and-error
