### ISSUE TITLE
What happens when a user is deleted?

### ISSUE THREAD

**Issue by ariejan** [kabisa/kudo-o-matic#379]
- [ ] Are his transactions kept?
 - [ ] Is his/her name kept?

**Comment by egonm12** [comment]
1. Are his transactions kept?
I think keeping them is important. It will not only affect the current balance in number of kudos but also reached goals can become unreached because of deleted transactions. 
2. Is his/her name kept?
I am not sure if this is legal according to the GDPR law but I would choose between keeping the current username or an anonymous username for deleted user (e.g. deleted-user-102, deleted-user-124, etc.)
