### ISSUE TITLE
Giving kudos to a team does not add any kudos to the team page

### ISSUE THREAD

**Issue by thnukid** [kabisa/kudo-o-matic#503]
**Describe the bug**
Can not give kudos in a team.

**To Reproduce**
1. Login
2. Choose "ASML Team"
3. Fill in 1 Kudo, Reciever: ASML Team, Message: for inviting me to the team.
4. Press Create
5. Flash message saying: "Post created successful"

**Expected behavior**
A new entry with the kudos, new kudos added to the meter. The kudo message is gone.

**Screenshots**
Fill in the message
![image](https://user-images.githubusercontent.com/1724804/51472094-cdf24b00-1d78-11e9-9779-13c8767686f6.png)

After pressing create
![image](https://user-images.githubusercontent.com/1724804/51472081-c3d04c80-1d78-11e9-86dc-c34588bc529d.png)

**Desktop (please complete the following information):**
 - OS: mac os x
 - Browser : chrome

**Comment by egonm12** [comment]
Hi @thnukid, thank you for reporting the issue! The bug you found is caused because the 'team user' is not a real user with email and password. We managed to fix this by skipping validations for 'virtual users' but since this would only work for new teams I needed to update it manually for existing teams. It should work fine now.

**Comment by thnukid** [comment]
👍 works now, thanks!
